apiVersion: v1
kind: Service
metadata:
  name: nodeuser-service
spec:
  selector:
    app: node-user
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 31111